### ISSUE TITLE
Examples not working on NO$PSX emulator

### ISSUE THREAD

**Issue by ivancosta** [spicyjpeg/ps1-bare-metal#1]
I'm trying to get a grip on PSX development, and your code is awesome!

However, the examples are only running on Duckstation, and dont run on NO$PSX. 

I think its important to run on NO$PSX because it features a very good debugger that other emulators don't have (watchpoints on memory, it do not hangs,, etc)

I hope the suggestion make it through
Ivan

**Comment by spicyjpeg** [comment]
I've just tested every example on the latest version of no$psx (v2.2, built-in BIOS) and they all seem to run just fine with the exception of the controllers one, which needed a small fix. I'm going to update the repo shortly.

Unfortunately, due to no$psx's idiosyncracies, getting the examples to run in the first place was quite an endeavor. I had to:

- change the extension of the generated executables from `.psexe` to `.exe`. The file picker will flat out refuse to load an executable if it does not have the `.exe` extension, *even if you select "All Files" from the file type dropdown*;
- move the ELF files the executables are converted from out of the build directory, as no$psx seemingly tries - and fails - to automatically parse debug symbols from them (possibly due to lacking support for newer ELF formats). There is an option to hide debug symbols in the settings, but it does not seem to actually prevent no$psx from attempting to parse the ELF files.

I would thus discourage using no$psx unless absolutely necessary, for instance to investigate code that breaks other emulators. For debugging purposes, [pcsx-redux](/grumpycoders/pcsx-redux) (not to be confused with PCSXR) is a far better option that gets updated regularly and comes with loads of debugging tools. DuckStation also has its own debugger and a GDB server, both accessible from the hidden-by-default debug menu albeit far more barebones than their pcsx-redux counterparts. Both emulators come with a dynamic recompiler enabled by default, so make sure you disable that and switch to interpreted CPU emulation in order for the debugging features to work properly.

**Comment by ivancosta** [comment]
Thanks for the advices.
I switched to pcsx-redux and it helped me a lot.

I've forked your code and added an example that shows how to call the PSX BIOS to make use of its printf function. I didn't find any such example when I needed it. Feel free to add to your code, if you may.

Cheers, Ivan
